DROP TABLE IF EXISTS groups CASCADE;
CREATE TABLE groups (id BIGINT NOT NULL PRIMARY KEY UNIQUE, name VARCHAR UNIQUE);
DROP TABLE IF EXISTS students;
DROP TYPE IF EXISTS genderEnum;
CREATE TYPE genderEnum AS ENUM ('MALE', 'FAMALE');
CREATE TABLE students (id BIGINT NOT NULL PRIMARY KEY UNIQUE, name VARCHAR, surename VARCHAR, groups_id BIGINT REFERENCES groups(id) ON DELETE SET NULL);